/**
 * Phase 16 — server-authoritative objective grading + flashcard validation
 * (§8.1, §10, §11). The server NEVER trusts client correctness or rating: it
 * reconstructs the objective question deterministically from the recorded
 * inputs using the SHARED study engine (never a parallel implementation),
 * verifies the recorded question identity, derives correctness from the entry
 * data, and maps the canonical rating. Flashcards cannot be objectively
 * regraded — only their self-rating is validated.
 *
 * PURE: operates only on the reconstructed release context + the submitted
 * fields. No server-only / DB imports.
 */
import { SOURCE_QUIZ_FORM_FIELDS } from "@/modules/content/constants";
import { serializeAnswerReference } from "@/modules/content/answer-reference";
import type { AnswerReference } from "@/modules/content/answer-reference";
import {
  createEntryAnswerResolver,
  deriveObjectiveCorrectness,
  generateQuestion,
  InvalidSelectionError,
  QuestionGenerationError,
  type ResolvedComponentIdentity,
} from "@/modules/study-engine";
import type { QuestionContext } from "@/modules/study-engine/generator";
import { ratingForAttempt, type SchedulerRating } from "@/modules/scheduler";
import {
  FLASHCARD_ALLOWED_RATINGS,
  type FlashcardAllowedRating,
} from "@/modules/sync/protocol";

/** The recorded objective-attempt fields the server needs to reconstruct + grade. */
export type ObjectiveAttemptFields = {
  identity: ResolvedComponentIdentity;
  mode: "mc" | "timed" | "test" | "timed_test";
  questionSeed: string;
  questionPosition: number;
  optionCount: number | null;
  promptField: string;
  questionInstanceId: string;
  questionGeneratorVersion: string;
  selectedAnswerRef: AnswerReference | null;
  hintUsed: boolean;
  /** Client CLAIM — retained only to detect/audit a mismatch, never trusted. */
  claimedIsCorrect: boolean;
};

export type ObjectiveGrade =
  | {
      ok: true;
      isCorrect: boolean;
      rating: SchedulerRating;
      correctAnswerRef: AnswerReference;
      questionInstanceId: string;
      /** The client's `is_correct` claim disagreed with the canonical result. */
      correctnessCorrected: boolean;
    }
  | {
      ok: false;
      reasonCode:
        | "unsupported_generator_version"
        | "question_mismatch"
        | "option_not_in_set";
    };

function isSourceField(
  field: string,
): field is (typeof SOURCE_QUIZ_FORM_FIELDS)[number] {
  return (SOURCE_QUIZ_FORM_FIELDS as readonly string[]).includes(field);
}

export function refsEqual(a: AnswerReference, b: AnswerReference): boolean {
  return serializeAnswerReference(a) === serializeAnswerReference(b);
}

/**
 * Reconstruct the objective question deterministically and derive the canonical
 * correctness + rating. Rejects a generator-version mismatch, a reconstruction
 * that doesn't match the recorded question id (tampered seed/inputs), or a
 * selected answer outside the reconstructed allowed set.
 */
export function gradeObjectiveAttempt(
  context: QuestionContext,
  attempt: ObjectiveAttemptFields,
): ObjectiveGrade {
  // The attempt must have been generated by the release's supported generator.
  if (attempt.questionGeneratorVersion !== context.questionGeneratorVersion) {
    return { ok: false, reasonCode: "unsupported_generator_version" };
  }

  // Reconstruct the question from the recorded deterministic inputs (never the
  // client's claimed allowed-set / correct answer).
  let instance;
  try {
    instance = generateQuestion(context, {
      identity: attempt.identity,
      deliveryMode: attempt.mode,
      questionSeed: attempt.questionSeed,
      position: attempt.questionPosition,
      // Entry-level prompt form (ignored for form_direction skills).
      promptForm: isSourceField(attempt.promptField)
        ? attempt.promptField
        : undefined,
      optionCount: attempt.optionCount ?? undefined,
    });
  } catch (error) {
    // A QuestionGenerationError is an expected reconstruction-divergence /
    // invalid-recorded-input signal → recoverable question_mismatch. ANY other
    // error is an internal defect (or a corrupt release entry) and MUST leave a
    // server-side trace rather than be silently indistinguishable from tamper.
    if (!(error instanceof QuestionGenerationError)) {
      console.error(
        `[sync] grade: unexpected question reconstruction failure for entry ${attempt.identity.entryId} skill ${attempt.identity.skillType} release ${context.releaseId}`,
        error,
      );
    }
    return { ok: false, reasonCode: "question_mismatch" };
  }

  // The reconstructed identity must match the recorded question id, or the
  // recorded inputs were tampered with.
  if (instance.questionInstanceId !== attempt.questionInstanceId) {
    return { ok: false, reasonCode: "question_mismatch" };
  }

  // An unanswered attempt (timeout / no selection) is simply incorrect.
  let isCorrect: boolean;
  if (attempt.selectedAnswerRef === null) {
    isCorrect = false;
  } else {
    const resolve = createEntryAnswerResolver(context.entriesById);
    try {
      isCorrect = deriveObjectiveCorrectness(
        instance,
        attempt.selectedAnswerRef,
        resolve,
      ).isCorrect;
    } catch (error) {
      if (error instanceof InvalidSelectionError) {
        return { ok: false, reasonCode: "option_not_in_set" };
      }
      throw error;
    }
  }

  const rating = ratingForAttempt({
    mode: attempt.mode,
    isCorrect,
    hintUsed: attempt.hintUsed,
  });

  return {
    ok: true,
    isCorrect,
    rating,
    correctAnswerRef: instance.correctAnswerRef,
    questionInstanceId: instance.questionInstanceId,
    correctnessCorrected: attempt.claimedIsCorrect !== isCorrect,
  };
}

/**
 * Flashcards are self-rated and cannot be objectively regraded (§11). The
 * canonical rating is derived from the self-grade; hints never downgrade a
 * flashcard. Structural component validation is done upstream (T5).
 */
export function gradeFlashcardAttempt(selfCorrect: boolean): {
  rating: SchedulerRating;
} {
  return {
    rating: ratingForAttempt({
      mode: "flashcard",
      isCorrect: selfCorrect,
      hintUsed: false,
    }),
  };
}

/**
 * A flashcard event's claimed rating must be one of the Phase 16-supported
 * self-ratings (Again / Good) — Hard and Easy are rejected for flashcards
 * (§11). Used by ingestion to reject an unsupported flashcard rating.
 */
export function isSupportedFlashcardRating(
  rating: string,
): rating is FlashcardAllowedRating {
  return (FLASHCARD_ALLOWED_RATINGS as readonly string[]).includes(rating);
}
